# Generated by Django 2.1.7 on 2019-04-04 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_resetpassowordtoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResetPassowordToken',
            new_name='ResetPasswordToken',
        ),
    ]
