# Generated by Django 2.1.7 on 2019-04-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20190404_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
