# Generated by Django 2.1.7 on 2019-04-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_verified'),
        ('authentication', '0003_auto_20190404_0631'),
    ]

    operations = [
    ]
