# Generated by Django 2.1.7 on 2019-04-09 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_social_id'),
        ('authentication', '0004_merge_20190404_1958'),
    ]

    operations = [
    ]
