# Generated by Django 2.1.7 on 2019-04-03 17:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='image/upload/v1554186175/samples/avatar.png', max_length=255, verbose_name='image'),
        ),
    ]
