# Generated by Django 2.1.7 on 2019-04-02 10:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/apibucket/image/upload/v1554188102/sample.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
