# Generated by Django 2.1.7 on 2019-04-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.TextField(default='https://res.cloudinary.com/dae3oj71g/image/upload/v1554186175/samples/avatar.png'),
        ),
    ]
