# Generated by Django 2.1.7 on 2019-04-03 11:02

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(default='image/upload/v1551960935/authors_haven.png', max_length=255, verbose_name='image')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(db_index=True, max_length=255)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_images', to='articles.Article')),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
    ]
