# Generated by Django 2.1.7 on 2019-04-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articleimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimage',
            name='description',
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.TextField(default='https://res.cloudinary.com/dv85uhrw5/image/upload/v1554278002/sample.jpg'),
        ),
    ]
