# Generated by Django 2.1.7 on 2019-04-09 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_article_read_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(null=True)),
                ('dislikes', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(db_column='article', on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='articles.Article', to_field='slug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_on',),
            },
        ),
    ]
