# Generated by Django 2.1.7 on 2019-04-04 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190403_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='articleimage',
            options={'ordering': ('-date_created',)},
        ),
    ]
