# Generated by Django 2.1.7 on 2019-04-11 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_likearticles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likearticles',
            name='dislikes',
        ),
    ]
