# Generated by Django 2.1.7 on 2019-04-09 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_reviewsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsmodel',
            name='rating_value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
