# Generated by Django 2.1.7 on 2019-04-13 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_likearticles_dislikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likearticles',
            name='article',
            field=models.ForeignKey(db_column='article', on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='articles.Article'),
        ),
    ]
