# Generated by Django 2.1.7 on 2019-04-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190409_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsmodel',
            name='rating_value',
            field=models.IntegerField(default=0),
        ),
    ]
