# Generated by Django 2.1.7 on 2019-04-11 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_likearticles_dislikes'),
        ('articles', '0003_auto_20190411_0738'),
    ]

    operations = [
    ]
