# Generated by Django 2.1.7 on 2019-04-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190409_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsmodel',
            name='review_body',
            field=models.TextField(blank=True),
        ),
    ]
