# Generated by Django 2.1.7 on 2019-04-12 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_likearticles_dislikes'),
        ('articles', '0006_auto_20190410_0636'),
    ]

    operations = [
    ]
