# Generated by Django 2.1.7 on 2019-04-15 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_merge_20190412_0220'),
        ('articles', '0007_auto_20190413_1111'),
    ]

    operations = [
    ]
