# Generated by Django 2.1.7 on 2019-04-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20190413_1111'),
        ('articles', '0005_merge_20190411_2029'),
    ]

    operations = [
    ]
