# Generated by Django 2.1.7 on 2019-04-17 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20190416_0856'),
        ('articles', '0008_merge_20190415_1304'),
    ]

    operations = [
    ]
